# Generated by Django 6.0.5 on 2026-05-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=500)),
                ('observacao', models.TextField(blank=True)),
            ],
        ),
    ]
